<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
      <LangVersion>latest</LangVersion>
      <AssemblyVersion>0.826.0.0</AssemblyVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MessagePack" Version="3.1.4" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\SharpBim.IssueTracker.Core\SharpBIM.IssueTracker.Core.csproj" />
	  <ProjectReference Include="..\..\..\SharpBIM\src\SharpBIM.csproj" />
  </ItemGroup>
 
   
    <ItemGroup>
      <Compile Update="Properties\Settings.Designer.cs">
        <DesignTimeSharedInput>True</DesignTimeSharedInput>
        <AutoGen>True</AutoGen>
        <DependentUpon>Settings.settings</DependentUpon>
      </Compile>
    </ItemGroup>
    <ItemGroup>
      <None Update="Properties\Settings.settings">
        <Generator>SettingsSingleFileGenerator</Generator>
        <LastGenOutput>Settings.Designer.cs</LastGenOutput>
      </None>
    </ItemGroup>
</Project>
