<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
      <LangVersion>latest</LangVersion>
      <AssemblyVersion>0.930.0.0</AssemblyVersion>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\SharpBIM\src\SharpBIM.csproj" />
    <ProjectReference Include="..\SharpBIM.IssueTracker.Core\SharpBIM.IssueTracker.Core.csproj" />
  </ItemGroup>
 
 
   
    <ItemGroup>
      <Compile Update="Properties\Settings.Designer.cs">
        <DesignTimeSharedInput>True</DesignTimeSharedInput>
        <AutoGen>True</AutoGen>
        <DependentUpon>Settings.settings</DependentUpon>
      </Compile>
    </ItemGroup>
    <ItemGroup>
      <None Update="Properties\Settings.settings">
        <Generator>SettingsSingleFileGenerator</Generator>
        <LastGenOutput>Settings.Designer.cs</LastGenOutput>
      </None>
    </ItemGroup>
</Project>
