<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<VisualStudioVersion Condition="'$(VisualStudioVersion)' == ''">18.0</VisualStudioVersion>
		<VSToolsPath Condition="'$(VSToolsPath)' == ''">$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)</VSToolsPath>
	</PropertyGroup>
	<Target Name="GenerateTemplatesManifest" />
	<Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" Condition="Exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props')" />
	<PropertyGroup>
		<Nullable>enable</Nullable>
		<LangVersion>latest</LangVersion>
		<AssemblyVersion>0.844.10.0</AssemblyVersion>
		<UseWPF>true</UseWPF>
		<Configurations>DWin;RWin</Configurations>
		<Platforms>x64</Platforms>
		<TargetFramework>net48</TargetFramework>
		<SchemaVersion>2.0</SchemaVersion>
		<!-- VSIX -->
		<ProjectTypeGuids>{82b43b9b-a64c-4715-b499-d71e9ca2bd60};{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}</ProjectTypeGuids>
		<GeneratePkgDefFile>true</GeneratePkgDefFile>
		<UseCodebase>true</UseCodebase>
		<CreateVsixContainer>True</CreateVsixContainer>
		<StartAction>Program</StartAction>
		<StartProgram Condition="'$(DevEnvDir)' != ''">$(DevEnvDir)devenv.exe</StartProgram>
		<StartArguments>/rootsuffix Exp</StartArguments>
		<XamlDebuggingInformation>True</XamlDebuggingInformation>
		<IncludeAssemblyInVSIXContainer>true</IncludeAssemblyInVSIXContainer>
		<IncludeDebugSymbolsInVSIXContainer>true</IncludeDebugSymbolsInVSIXContainer>
		<IncludeDebugSymbolsInLocalVSIXDeployment>false</IncludeDebugSymbolsInLocalVSIXDeployment>
		<CopyBuildOutputToOutputDirectory>true</CopyBuildOutputToOutputDirectory>
		<CopyOutputSymbolsToOutputDirectory>true</CopyOutputSymbolsToOutputDirectory>
		<GenerateTemplateManifests>false</GenerateTemplateManifests>
		<ExcludeFromVsixSources>true</ExcludeFromVsixSources>
		<VSSDKBuildToolsAutoSetup>true</VSSDKBuildToolsAutoSetup>
		<VsixDeployOnDebug>true</VsixDeployOnDebug>
	</PropertyGroup>
	<ItemGroup>
	  <Compile Remove="Images\**" />
	  <EmbeddedResource Remove="Images\**" />
	  <None Remove="Images\**" />
	  <Page Remove="Images\**" />
	</ItemGroup>
	<ItemGroup>
		<ProjectCapability Include="CreateVsixContainer" />
	</ItemGroup>
	<PropertyGroup>
		<RestoreProjectStyle>PackageReference</RestoreProjectStyle>
		<CopyVsixExtensionLocation>D:\RevitAPI\Shared\Lib\Compiled\Revit\ExternalLibraries\SharpBIM.IssueTracker\Vsix</CopyVsixExtensionLocation>
		<SignAssembly>False</SignAssembly>
		<DelaySign>False</DelaySign>
	</PropertyGroup>
	<PropertyGroup Condition="$(Configuration.ToLower().StartsWith('d'))">
		<DebugSymbols>true</DebugSymbols>
		<DebugType>full</DebugType>
		<OutputPath>bin\DWin\</OutputPath>
		<DefineConstants>DEBUG;TRACE</DefineConstants>
		<DeployExtension>true</DeployExtension>
		<PlatformTarget>x64</PlatformTarget>
	</PropertyGroup>
	<PropertyGroup Condition="$(Configuration.ToLower().StartsWith('r'))">
		<DebugType>pdbonly</DebugType>
		<OutputPath>bin\RWin\</OutputPath>
		<DeployExtension>false</DeployExtension>
		<PlatformTarget>x64</PlatformTarget>
	</PropertyGroup>
	<ItemGroup>
		<Compile Update="source.extension.cs">
			<AutoGen>True</AutoGen>
			<DesignTime>True</DesignTime>
			<DependentUpon>source.extension.vsixmanifest</DependentUpon>
		</Compile>
		<Compile Update="VSCommandTable.cs">
		  <DesignTime>True</DesignTime>
		  <AutoGen>True</AutoGen>
		  <DependentUpon>VSCommandTable.vsct</DependentUpon>
		</Compile>
	</ItemGroup>
	<ItemGroup>
		<VSCTCompile Include="VSCommandTable.vsct">
			<ResourceName>Menus.ctmenu</ResourceName>
			<Generator>VsctGenerator</Generator>
			<LastGenOutput>VSCommandTable.cs</LastGenOutput>
		</VSCTCompile>
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="Community.VisualStudio.VSCT" Version="16.0.29.14" PrivateAssets="all" />
		<PackageReference Include="Microsoft.VSSDK.BuildTools" Version="18.5.40034">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="Community.VisualStudio.Toolkit.17" Version="17.0.551" ExcludeAssets="Runtime">
			<IncludeAssets>compile; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="SharpBIM-Rwin" Version="1.1.361.0" Condition="$(Configuration.ToLower().StartsWith('r'))" />
	</ItemGroup>
	<ItemGroup>
		<Folder Include="Properties\" />
	</ItemGroup>
	<ItemGroup Condition="$(Configuration.ToLower().StartsWith('d'))">
	  <ProjectReference Include="..\..\..\SharpBIM\src\SharpBIM.csproj" />
	  <ProjectReference Include="..\SharpBIM.IssueTracker.Core\SharpBIM.IssueTracker.Core.csproj" />
	</ItemGroup>
	<ItemGroup>
	  <SuppressFromVsix Remove="Images\**" />
	</ItemGroup>
	<ItemGroup>
	  <VSCTInclude Remove="Images\**" />
	</ItemGroup>
	<ItemGroup>
	  <None Remove="IssueTracker_128x128.png" />
	</ItemGroup>
	<ItemGroup>
	  <Content Include="IssueTracker_128x128.png" />
	</ItemGroup>
	<ItemGroup>
	  <None Update="source.extension.vsixmanifest">
	    <Generator>VsixManifestGenerator</Generator>
	    <LastGenOutput>source.extension.cs</LastGenOutput>
	  </None>
	</ItemGroup>
	 
	 
 </Project>
