// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.47
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SharpBIM.IssueTracker
{
    using System;

    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string IconListString = "aef89497-74ab-4922-9c76-ddb24b8fdb21";
        public static Guid IconList = new Guid(IconListString);

        public const string SharpBIMTrackerMainMenuString = "24e154c4-bab4-4467-9480-1ec41b2342dc";
        public static Guid SharpBIMTrackerMainMenu = new Guid(SharpBIMTrackerMainMenuString);

        public const string SharpBIMTrackerPackageString = "dc5502ec-39af-432d-b9be-1fa7b25054ac";
        public static Guid SharpBIMTrackerPackage = new Guid(SharpBIMTrackerPackageString);

        public const string SharpBIMTrackerCommandString = "b52a8b31-6237-4c5f-85f2-172bbd16ec91";
        public static Guid SharpBIMTrackerCommand = new Guid(SharpBIMTrackerCommandString);
    }

    /// <summary>
    /// Helper class that encapsulates all CommandIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int GitWindowImg = 0x0001;
        public const int MyMenuGroup = 0x1020;
        public const int MyCommand = 0x0100;
    }
}
