<Project Sdk="Microsoft.NET.Sdk">
	
	<PropertyGroup Condition="'$(Configuration)' == 'SA'">
		<AssemblyVersion>0.930.1.0</AssemblyVersion>
		<StartupObject>SharpBIM.IssueTracker.Core.WPF.SA.App</StartupObject>
		<OutputType>WinExe</OutputType>
	</PropertyGroup>
	<Import Project="..\SolutionItems\SharpBIM.Defaults.props" />
	
	<ItemGroup Condition="!$(Configuration.Contains('SA'))">
		<Compile Remove="WPF\SA\**" />
		<Compile Remove="WPF\SA\**" />
		<EmbeddedResource Remove="WPF\SA\**" />
		<None Remove="WPF\SA\**" />
		<Page Remove="WPF\SA\**" />
	</ItemGroup>
	<ItemGroup Condition="!($(DefineConstants.Contains('WINDOWS')))">
		<Compile Remove="WPF\**" />
		<EmbeddedResource Remove="WPF\**" />
		<None Remove="WPF\**" />
		<Page Remove="WPF\**" />
	</ItemGroup>
 
	<ItemGroup>
		<Resource Include="Resources\tickets_Login.png" />
	</ItemGroup>
 
	<ItemGroup>
		<Compile Remove="GitHttp\Models\**" />
		<EmbeddedResource Remove="GitHttp\Models\**" />
		<None Remove="GitHttp\Models\**" />
		<VSCTInclude Remove="WPF\Mvvm\Views\Views\**" />
	</ItemGroup>
	<ItemGroup Condition="'$(Configuration)' == 'SA'">
		<ApplicationDefinition Include="WPF/SA/App.xaml" />
	</ItemGroup>
	<ItemGroup>
		<Page Remove="WPF\Helpers\Markdown.Style.xaml" />
	</ItemGroup>
	<ItemGroup>
		<Compile Include="GitHttp\Models\User.cs" />
	</ItemGroup>
	<ItemGroup Condition="$(Configuration.ToLower().StartsWith('r'))">
	  <Reference Include="SharpBIM">
	    <HintPath>$(RevitlibPath)\ExternalLibraries\SharpBIM\$(Configuration)\$(TargetFramework)\SharpBIM.dll</HintPath>
	  </Reference>
	</ItemGroup>
 
	<ItemGroup Condition="!$(DefineConstants.Contains('DOTNET'))">
	  <Reference Include="System.Web" />
	</ItemGroup>
	<ItemGroup Condition="$(Configuration.ToLower().StartsWith('d')) OR $(Configuration.ToLower().StartsWith('sa'))">
		<ProjectReference Include="..\..\..\SharpBIM\src\SharpBIM.csproj" />
	</ItemGroup>
</Project>
