<Project Sdk="Microsoft.NET.Sdk">
	
	<PropertyGroup Condition="'$(Configuration)' == 'SA'">
		<AssemblyVersion>0.830.1.0</AssemblyVersion>
		<StartupObject>SharpBIM.IssueTracker.Core.WPF.SA.App</StartupObject>
		<RuntimeIdentifiers>win</RuntimeIdentifiers>
		<OutputType>WinExe</OutputType>
	</PropertyGroup>
	<Import Project="..\SolutionItems\SharpBIM.Defaults.props" />
	
	<ItemGroup Condition="!$(Configuration.Contains('SA'))">
		<Compile Remove="WPF\SA\**" />
		<Compile Remove="WPF\SA\**" />
		<EmbeddedResource Remove="WPF\SA\**" />
		<None Remove="WPF\SA\**" />
		<Page Remove="WPF\SA\**" />
	</ItemGroup>
	<ItemGroup Condition="!($(DefineConstants.Contains('WINDOWS')))">
		<Compile Remove="WPF\**" />
		<EmbeddedResource Remove="WPF\**" />
		<None Remove="WPF\**" />
		<Page Remove="WPF\**" />
	</ItemGroup>
	
	<ItemGroup Condition="($(DefineConstants.Contains('WINDOWS')))">
		<PackageReference Include="HtmlAgilityPack">
			<Version>1.12.4</Version>
		</PackageReference>
	</ItemGroup>
	<ItemGroup>
		<Resource Include="Resources\tickets_Login.png" />
	</ItemGroup>
 
	<ItemGroup>
		<Compile Remove="GitHttp\Models\**" />
		<EmbeddedResource Remove="GitHttp\Models\**" />
		<None Remove="GitHttp\Models\**" />
		<VSCTInclude Remove="WPF\Mvvm\Views\Views\**" />
	</ItemGroup>
	<ItemGroup Condition="'$(Configuration)' == 'SA'">
		<ApplicationDefinition Include="WPF/SA/App.xaml" />
	</ItemGroup>
	<ItemGroup Condition="  ($(Configuration.StartsWith('D')) OR $(Configuration.StartsWith('SA')))">
		<PackageReference Include="AvalonEdit" Version="6.3.1.120" />
		<PackageReference Include="MdXaml">
			<Version>2.0.0-pre202603081301</Version>
		</PackageReference>
		<PackageReference Include="Auth0.OidcClient.WPF" Version="4.1.0" />
		<PackageReference Include="BouncyCastle.Cryptography" Version="2.7.0-beta.98" />
		<PackageReference Include="envdte100" Version="17.14.40260" />
		<PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.5.0" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.5.0" />
		<PackageReference Include="Microsoft.VisualStudio.Utilities" Version="17.14.40264" />
		<PackageReference Include="System.Net.Http" Version="4.3.4" />
		<Reference Include="System.Web" Condition="!$(DefineConstants.Contains('DOTNET'))" />
		<ProjectReference Include="..\..\..\SharpBIM\src\SharpBIM.csproj" />
	</ItemGroup>
	<ItemGroup>
		<Page Remove="WPF\Helpers\Markdown.Style.xaml" />
	</ItemGroup>
	<ItemGroup>
		<Compile Include="GitHttp\Models\User.cs" />
	</ItemGroup>
	<ItemGroup Condition="$(Configuration.StartsWith('R'))">
	  <Reference Include="SharpBIM">
	    <HintPath>$(RevitlibPath)\ExternalLibraries\SharpBIM\$(Configuration)\$(TargetFramework)\SharpBIM.dll</HintPath>
	  </Reference>
	</ItemGroup>
	<ItemGroup>
	  <PackageReference Include="AvalonEdit" Version="6.3.1.120" />
	  <PackageReference Include="IdentityModel.OidcClient" Version="5.2.1" />
	  <PackageReference Include="System.Text.Json" Version="10.0.4" />
	</ItemGroup>
	<ItemGroup Condition="!$(DefineConstants.Contains('DOTNET'))" >
	  <Reference Include="System.Web" />
	</ItemGroup>
</Project>
