<Project>
    <Import Project=".\SharpBIM.Identity.props" />
    <PropertyGroup >
        <RevitBuild >false</RevitBuild>

    </PropertyGroup>
    <PropertyGroup Condition="Exists('.\SharpBIM.RevitDefaults.props')">
        <RevitBuild>true</RevitBuild>
        <DefineConstants>$(DefineConstants);WINDOWS</DefineConstants>
    </PropertyGroup>
    <Import Condition="$(RevitBuild)" Project=".\SharpBIM.RevitDefaults.props"/>
    <PropertyGroup>
        <AppendTargetFrameworkToOutputPath Condition="!$(RevitBuild)">true</AppendTargetFrameworkToOutputPath>
        <Configurations Condition="!$(RevitBuild)" >DWin;RWin;DNoWin;RNoWin;SA</Configurations>
    </PropertyGroup>
    <PropertyGroup Condition="$(RevitBuild)">
        <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>    </PropertyGroup>
    <PropertyGroup Condition="(!$(RevitBuild) AND (!$(Configuration.ToLower().Contains('nowin')) OR '$(Configuration)' == 'SA'))">
        <TargetFrameworks Condition="'$(TargetFrameworks)' == ''" >net47;net472;net48;net8.0-windows8;net10.0-windows8</TargetFrameworks>
        <DefineConstants>$(DefineConstants);WINDOWS</DefineConstants>
    </PropertyGroup>
    <PropertyGroup Condition="(!$(RevitBuild) AND $(Configuration.ToLower().Contains('nowin')))">
        <TargetFrameworks Condition="'$(TargetFrameworks)' == ''">net47;net472;net48;net8.0;net10.0</TargetFrameworks>
        <DefineConstants>$(DefineConstants);WEB</DefineConstants>
    </PropertyGroup>
    <!-- Configuration-specific settings -->
    <PropertyGroup Condition="$(Configuration.ToLower().StartsWith('d')) OR $(Configuration.ToLower().StartsWith('sa'))">
        <IsDebug>true</IsDebug>
        <DebugSymbols>true</DebugSymbols>
        <DebugType>full</DebugType>
        <DebugRelease>Debug</DebugRelease>
        <DefineConstants>$(DefineConstants);DEBUG;TRACE</DefineConstants>
        <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    </PropertyGroup>
    <PropertyGroup Condition="$(Configuration.ToLower().StartsWith('r'))">
        <DebugSymbols>false</DebugSymbols>
        <IsDebug>false</IsDebug>
        <DebugRelease>Release</DebugRelease>

        <DefineConstants>$(DefineConstants);RELEASE</DefineConstants>
    </PropertyGroup>
    <!-- Framework-specific settings -->
    <PropertyGroup Condition="$(TargetFramework.Contains('net47'))">
        <DefineConstants>$(DefineConstants);FRAMEWORK47</DefineConstants>
    </PropertyGroup>
    <PropertyGroup Condition="'$(TargetFramework)' == 'net48'">
        <DefineConstants>$(DefineConstants);FRAMEWORK48</DefineConstants>
    </PropertyGroup>
    <PropertyGroup Condition="'$(TargetFramework)' == 'netstandard2.0'">
        <DefineConstants>$(DefineConstants);NETCOREAPP</DefineConstants>
    </PropertyGroup>
    <PropertyGroup Condition="$(TargetFramework.Contains('net8.0'))">
        <DefineConstants>$(DefineConstants);DOTNET8;DOTNET</DefineConstants>
        <RuntimeFrameworkVersion>8.0.0</RuntimeFrameworkVersion>
    </PropertyGroup>
    <PropertyGroup Condition="$(TargetFramework.Contains('net10.0'))">
        <DefineConstants>$(DefineConstants);DOTNET10;DOTNET</DefineConstants>
        <RuntimeFrameworkVersion>10.0.0</RuntimeFrameworkVersion>
    </PropertyGroup>
    <PropertyGroup Condition="$(DefineConstants.Contains('WINDOWS'))">
        <UseWPF>true</UseWPF>
        <UseWindowsForms>true</UseWindowsForms>
    </PropertyGroup>
    <Choose>
        <When Condition="$(DefineConstants.Contains('DOTNET'))">
            <ItemGroup>
                <Reference Include="License">
                    <HintPath>d:\Program Files (x86)\Eziriz\.NET Reactor\SDK\Binaries\License.dll .NET 6\License.dll</HintPath>
                    <Private>False</Private>
                </Reference>
                <Reference Include="LicenseGenerator">
                    <HintPath>d:\Program Files (x86)\Eziriz\.NET Reactor\SDK\Binaries\LicenseGen.dll</HintPath>
                    <Private>False</Private>
                </Reference>
            </ItemGroup>
        </When>
        <When Condition="!$(DefineConstants.Contains('DOTNET'))">
            <ItemGroup>
                <Reference Include="License">
                    <HintPath>d:\Program Files (X86)\Eziriz\.NET Reactor\SDK\Binaries\License.dll .NET 4.x\License.dll</HintPath>
                    <Private >false</Private>
                </Reference>
                <Reference Include="LicenseGenerator">
                    <HintPath>d:\Program Files (x86)\Eziriz\.NET Reactor\SDK\Binaries\LicenseGenNetStandard.dll</HintPath>
                    <Private>false</Private>
                </Reference>
            </ItemGroup>
        </When>
    </Choose>
    <ItemGroup>
        <Compile Remove="solutionitems\**" />
        <EmbeddedResource Remove="solutionitems\**" />
        <None Remove="solutionitems\**" />
        <Page Remove="solutionitems\**" />
    </ItemGroup>
    <ItemGroup>
        <None Include="sqlite3.dll"
        Condition="Exists('$(MSBuildProjectDirectory)\sqlite3.dll')">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>
    <ItemGroup>
        <Compile Remove="*.bundle\**" />
        <EmbeddedResource Remove="*.bundle\**" />
        <None Remove="*.bundle\**" />
        <Page Remove="*.bundle\**" />
    </ItemGroup>
    <ItemGroup Condition="$(DefineConstants.Contains('WINDOWS'))">
        <PackageReference  Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.135" />
        <PackageReference Include="Microsoft.VisualStudio.Utilities" Version="17.14.40264" />
        <PackageReference Condition="!$(DefineConstants.Contains('DOTNET'))" Include="PresentationFramework.Aero2" Version="1.0.1" />
        <PackageReference Include="AvalonEdit" Version="6.3.1.120" />
        <PackageReference Include="MdXaml" Version="2.0.0-pre202603081301" />
        <PackageReference Include="HtmlAgilityPack" Version ="1.12.4"/>
    </ItemGroup>
    <ItemGroup Condition="!$(DefineConstants.Contains('WINDOWS'))">
        <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Auth0.OidcClient.WPF" Version="4.1.0" />
        <PackageReference Include="BouncyCastle.Cryptography" Version="2.7.0-beta.98" />
        <PackageReference Include="envdte100" Version="17.14.40260" />
        <PackageReference Include="Markdig" Version="1.2.0" />
        <PackageReference Include="Microsoft.Bcl.Memory" Version="9.0.14" />
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.13.0" />
        <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
        <PackageReference Include="System.Text.Json" Version="10.0.4" />
        <PackageReference Include="System.Net.Http" Version="4.3.4" />
        <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.5.0" />
        <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.5.0" />
        <Reference Include="System.Web" Condition="!$(DefineConstants.Contains('DOTNET'))" />
    </ItemGroup>
    <ItemGroup>
        <None Update="Services\DataBaseService\Database\sqlite3.dll" TargetPath="sqlite3.dll">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
    </ItemGroup>
    <PropertyGroup>
    		<!-- <OutputPath >.\bin\$(DebugRelease)</OutputPath> -->
    		<OutputPath Condition="$(RevitBuild)" >.\bin\$(DebugRelease)\$(RVersion)</OutputPath>
    </PropertyGroup>
</Project>