<Project>
    <Import Project=".\SharpBIM.Identity.props" />
    <PropertyGroup>
        <AppendTargetFrameworkToOutputPath>true</AppendTargetFrameworkToOutputPath>
        <Configurations>DWin;RWin;DNoWin;RNoWin;SA</Configurations>
    </PropertyGroup>
    <PropertyGroup Condition="(!$(Configuration.ToLower().Contains('nowin')) OR '$(Configuration)' == 'SA')">
        <TargetFrameworks Condition="'$(TargetFrameworks)' == ''" >net47;net472;net48;net8.0-windows8;net10.0-windows8</TargetFrameworks>
        <DefineConstants>$(DefineConstants);WINDOWS</DefineConstants>
    </PropertyGroup>
    <PropertyGroup Condition="$(Configuration.ToLower().Contains('nowin'))">
        <TargetFrameworks Condition="'$(TargetFrameworks)' == ''">net47;net472;net48;net8.0;net10.0</TargetFrameworks>
        <DefineConstants>$(DefineConstants);WEB</DefineConstants>
    </PropertyGroup>
    <!-- Configuration-specific settings -->
    <PropertyGroup Condition="$(Configuration.ToLower().StartsWith('d')) OR $(Configuration.ToLower().StartsWith('sa'))">
        <IsDebug>true</IsDebug>
        <DebugSymbols>true</DebugSymbols>
        <DebugType>full</DebugType>
        <DefineConstants>$(DefineConstants);DEBUG;TRACE</DefineConstants>
        <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    </PropertyGroup>
    <PropertyGroup Condition="$(Configuration.ToLower().StartsWith('r'))">
        <DebugSymbols>false</DebugSymbols>
        <IsDebug>false</IsDebug>
        <DefineConstants>$(DefineConstants);RELEASE</DefineConstants>
    </PropertyGroup>
    <!-- Framework-specific settings -->
    <PropertyGroup Condition="$(TargetFramework.Contains('net47'))">
        <DefineConstants>$(DefineConstants);FRAMEWORK47</DefineConstants>
    </PropertyGroup>
    <PropertyGroup Condition="'$(TargetFramework)' == 'net48'">
        <DefineConstants>$(DefineConstants);FRAMEWORK48</DefineConstants>
    </PropertyGroup>
    <PropertyGroup Condition="'$(TargetFramework)' == 'netstandard2.0'">
        <DefineConstants>$(DefineConstants);NETCOREAPP</DefineConstants>
    </PropertyGroup>
    <PropertyGroup Condition="$(TargetFramework.Contains('net8.0'))">
        <DefineConstants>$(DefineConstants);DOTNET8;DOTNET</DefineConstants>
        <RuntimeFrameworkVersion>8.0.0</RuntimeFrameworkVersion>
    </PropertyGroup>
    <PropertyGroup Condition="$(TargetFramework.Contains('net10.0'))">
        <DefineConstants>$(DefineConstants);DOTNET10;DOTNET</DefineConstants>
        <RuntimeFrameworkVersion>10.0.0</RuntimeFrameworkVersion>
    </PropertyGroup>
    <PropertyGroup Condition="$(DefineConstants.Contains('WINDOWS'))">
        <UseWPF>true</UseWPF>
        <UseWindowsForms>true</UseWindowsForms>
    </PropertyGroup>
    <Choose>
        <When Condition="$(DefineConstants.Contains('DOTNET'))">
            <ItemGroup>
                <Reference Include="License">
                    <HintPath>d:\Program Files (x86)\Eziriz\.NET Reactor\SDK\Binaries\License.dll .NET 6\License.dll</HintPath>
                    <Private>False</Private>
                </Reference>
                <Reference Include="LicenseGenerator">
                    <HintPath>d:\Program Files (x86)\Eziriz\.NET Reactor\SDK\Binaries\LicenseGen.dll</HintPath>
                    <Private>False</Private>
                </Reference>
            </ItemGroup>
        </When>
        <When Condition="!$(DefineConstants.Contains('DOTNET'))">
            <ItemGroup>
                <Reference Include="License">
                    <HintPath>d:\Program Files (X86)\Eziriz\.NET Reactor\SDK\Binaries\License.dll .NET 4.x\License.dll</HintPath>
                    <Private >false</Private>
                </Reference>
                <Reference Include="LicenseGenerator">
                    <HintPath>d:\Program Files (x86)\Eziriz\.NET Reactor\SDK\Binaries\LicenseGenNetStandard.dll</HintPath>
                    <Private>false</Private>
                </Reference>
            </ItemGroup>
        </When>
    </Choose>
    <ItemGroup>
        <Compile Remove="solutionitems\**" />
        <EmbeddedResource Remove="solutionitems\**" />
        <None Remove="solutionitems\**" />
        <Page Remove="solutionitems\**" />
    </ItemGroup>
    <ItemGroup>
        <None Include="sqlite3.dll"
        Condition="Exists('$(MSBuildProjectDirectory)\sqlite3.dll')">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>
    <ItemGroup>
        <Compile Remove="*.bundle\**" />
        <EmbeddedResource Remove="*.bundle\**" />
        <None Remove="*.bundle\**" />
        <Page Remove="*.bundle\**" />
    </ItemGroup>
    <ItemGroup Condition="$(DefineConstants.Contains('WINDOWS'))">
        <PackageReference  Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.135" />
        <PackageReference Include="Microsoft.VisualStudio.Utilities" Version="17.14.40264" />
        <PackageReference Condition="!$(DefineConstants.Contains('DOTNET'))" Include="PresentationFramework.Aero2" Version="1.0.1" />
    </ItemGroup>
</Project>