<Project>
    <PropertyGroup>
        <AppendRuntimeIdentifierToOutputPath>true</AppendRuntimeIdentifierToOutputPath>
        <AppendTargetFrameworkToOutputPath>true</AppendTargetFrameworkToOutputPath>
        <Authors>Moustafa K. Elsayed</Authors>
        <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
      
        <Company>SharpBIM</Company>
        <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
        <Copyright>(c) SharpBIM</Copyright>
        <DebugSymbols>true</DebugSymbols>
        <Deterministic>false</Deterministic>
        <EnableTargetFrameworkAlias>true</EnableTargetFrameworkAlias>
        <GenerateAssemblyFileVersionAttribute>true</GenerateAssemblyFileVersionAttribute>
        <ImplicitUsings>disabled</ImplicitUsings>
        <LangVersion>latest</LangVersion>
        <NoWarn>*</NoWarn>
        <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
        <NeutralLanguage>en</NeutralLanguage>
        <OutputType Condition="'$(OutputType)' == ''">Library</OutputType>
        <GenerateSatelliteAssembliesForCore>false</GenerateSatelliteAssembliesForCore>
        <GenerateAssemblyConfigurationAttribute>true</GenerateAssemblyConfigurationAttribute>
        <Product>SharpBIM</Product>
        <PublishSingleFile>false</PublishSingleFile>
        <RestorePackages>false</RestorePackages>
        <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
        <XamlDebuggingInformation>True</XamlDebuggingInformation>
        <PackageId>$(AssemblyName)-$(Configuration)</PackageId>
        <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
        <PreserveCompilationContext>true</PreserveCompilationContext>
        <ForceDesignerDPIUnaware>true</ForceDesignerDPIUnaware>
        <GenerateDocumentationFile>false</GenerateDocumentationFile>
        <DisableImplicitNuGetFallbackFolder>true</DisableImplicitNuGetFallbackFolder>
        		<Platforms>x64</Platforms>

        <SignAssembly>False</SignAssembly>
        <DefineConstants>$(DefineConstants);TxtJson</DefineConstants>
    </PropertyGroup>
</Project>