// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SharpBim.GitTracker
{
    internal sealed partial class Vsix
    {
        public const string Id = "SharpBIM.GitTracker.201D8256-D3A5-4AAC-9911-DA17EF82BB0D";
        public const string Name = "Issue Tracker";
        public const string Description = @"An  application designed to help users visualize and manage issues within Visual Studio. It provides a streamlined interface for tracking and addressing common problems, offering an intuitive way to view issue details and take action directly from the application.";
        public const string Language = "en-US";
        public const string Version = "0.60";
        public const string Author = "SharpBIM";
        public const string Tags = "issue, Tracker, Github Issues, tickets";
    }
}
