// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SharpBim.GitTracker
{
    internal sealed partial class Vsix
    {
        public const string Id = "GenerateMvvm.5092b9ba-e35d-4c64-b831-b34fda31135b";
        public const string Name = "GenerateMvvm";
        public const string Description = @"a trial test to know how to use vsix";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Moustafa Elsayed";
        public const string Tags = "";
    }
}
