// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SharpBim.GitTracker
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string SharpBIMGitTrackerString = "3f0acd17-c5e8-42a1-babb-9e81f813533c";
        public static Guid SharpBIMGitTracker = new Guid(SharpBIMGitTrackerString);

        public const string guidSHLMainMenuString = "d309f791-903f-11d0-9efc-00a0c911004f";
        public static Guid guidSHLMainMenu = new Guid(guidSHLMainMenuString);

        public const string guidKnownImageIdsString = "ae27a6b0-e345-4288-96df-5eaf394ee369";
        public static Guid guidKnownImageIds = new Guid(guidKnownImageIdsString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x0001;
        public const int ShowTrackerWindowCommand = 0x0100;
    }
}