// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SharpBim.GitTracker
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string IconListString = "6f986d7f-725a-4a39-8a0e-5b668c90bed0";
        public static Guid IconList = new Guid(IconListString);

        public const string SharpBIMGitTrackerPackageString = "7db12793-ba27-49f2-8664-ebcab7bb8ceb";
        public static Guid SharpBIMGitTrackerPackage = new Guid(SharpBIMGitTrackerPackageString);

        public const string ShowTrackerWindowCommandGuidString = "89b9a33a-9d0c-494b-a1bc-7b5ddda5a3ec";
        public static Guid ShowTrackerWindowCommandGuid = new Guid(ShowTrackerWindowCommandGuidString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int GitWindowImg = 0x0001;
        public const int MyMenuGroup = 0x1020;
        public const int ShowTrackerWindowCommand = 0x0100;
    }
}